name: globaldatingchat
description: "Global Dating Chat - Connect with people worldwide"
publish_to: 'none'
version: 1.0.8+9

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^20.3.1
  lucide_icons: ^0.257.0
  country_picker: ^2.0.27
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  image: ^4.0.17
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  camera: ^0.11.3
  http: ^1.5.0
  livekit_client: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
